"""Cadastros patrimoniais e documentos que suportam os eventos dos bens."""
def register(C,F,R,ref,choice,money,day,qty,text):
 r=C['assets']['resources'];base=lambda:dict(code=F('Código / número',required=True),name=F('Descrição',required=True))
 r['responsibles']=R('Responsáveis por bens e locais',{**base(),'cpf':F('CPF','cpf',True),'admission':choice('Forma de ingresso','Admissão em emprego público|Eleição|Nomeação de cargo efetivo|Nomeação de cargo comissionado'),'relationship':choice('Vínculo','Cargo efetivo|Cargo comissionado|Cargo eletivo|Estagiário|Prestador de serviços'),'active':F('Ativo','boolean')})
 r['locations']=R('Localizações patrimoniais',{**base(),'address':F('Endereço',required=True),'responsible':ref('Responsável','assets.responsibles'),'active':F('Ativa','boolean')})
 r['commissions']=R('Comissões patrimoniais',{**base(),'type':choice('Finalidade','Avaliação|Inventário|Recebimento'),'created':day('Criação',True),'extinguished':day('Extinção'),'legal_basis':text('Ato de designação',True)},operations=['seal_asset_commission'])
 r['commission_members']=R('Integrantes de comissões patrimoniais',{**base(),'commission':ref('Comissão','assets.commissions'),'responsible':ref('Integrante','assets.responsibles'),'role':F('Cargo na comissão',required=True)})
 r['classes']['fields'].update(nature=choice('Natureza','Móvel|Imóvel|Intangível|Infraestrutura|Semovente',False),useful_years=qty('Vida útil (anos; alternativa aos meses)'),proration=choice('Critério de proporcionalidade','Dias corridos|Mês integral',False))
 r['classes']['fields']['useful_months']['required']=False
 r['accounting_rules']=R('Regras contábeis patrimoniais',{**base(),'class':ref('Classificação específica (vazio = padrão)','assets.classes',False),'fact':choice('Fato','Ingresso|Depreciação|Reavaliação positiva|Redução de valor|Baixa|Valor complementar|Doação recebida|Doação concedida'),'counterpart':ref('Conta de contrapartida','finance.accounts'),'legal_basis':text('Fundamentação contábil',True)},operations=['approve_asset_rule','retire_asset_rule'])
 r['items']['fields'].update(registry=F('Certidão de registro'),registration=F('Matrícula'),responsible=ref('Responsável cadastrado','assets.responsibles',False),location_ref=ref('Local cadastrado','assets.locations',False),receipt_commission=ref('Comissão de recebimento','assets.commissions',False),ingress_type=choice('Tipo de ingresso','Aquisição|Doação|Construção|Implantação|Comodato|Locação',False),capitalize=F('Ativar na contabilidade','boolean'),useful_years=qty('Vida útil específica (anos)'),residual_percent=F('Residual específico (%)','percent'),tombamento=F('Dados do tombamento'),process=ref('Processo licitatório de aquisição','procurement.processes',False),commitment=ref('Empenho de aquisição','finance.commitments',False),invoice=F('Nota fiscal / série'),requires_confirmation=F('Exigir conferência no recebimento','boolean'),situation=choice('Situação de uso','Em uso|Em reserva|Em manutenção|Inservível',False))
 r['items']['operations']=['activate_asset','confirm_asset_receipt','depreciate','transfer_asset','reclassify_asset','revise_asset_identity','writeoff_asset','reverse_asset_event']
 r['valuations']=R('Avaliações patrimoniais',{**base(),'asset':ref('Bem','assets.items'),'commission':ref('Comissão de avaliação','assets.commissions'),'date':day('Avaliação',True),'type':choice('Avaliação','Reavaliação|Redução ao valor recuperável'),'amount':money('Novo valor contábil',True),'method':choice('Novo método','Quotas constantes|Unidades produzidas|Não depreciável'),'useful_months':F('Vida útil remanescente em meses','integer',True),'residual_percent':F('Residual (%)','percent',True),'total_units':qty('Produção estimada do novo ciclo'),'units':qty('Produção ainda não depreciada do ciclo anterior'),'situation':choice('Situação','Em uso|Em reserva|Em manutenção|Inservível'),'report':text('Laudo e fundamentação',True)},operations=['apply_asset_valuation'])
 r['complements']=R('Valores complementares',{**base(),'asset':ref('Bem','assets.items'),'date':day('Fato',True),'ingress_type':choice('Tipo de ingresso','Aquisição|Construção|Doação|Implantação'),'supplier':ref('Fornecedor','procurement.suppliers',False),'amount':money('Valor complementar',True),'process':ref('Processo licitatório','procurement.processes',False),'reason':text('Descrição do custo subsequente',True)},operations=['apply_asset_complement'])
 r['complement_commitments']=R('Empenhos de valores complementares',{**base(),'complement':ref('Valor complementar','assets.complements'),'commitment':ref('Empenho','finance.commitments'),'amount':money('Valor vinculado',True)})
 r['insurances']=R('Seguros de bens',{**base(),'asset':ref('Bem','assets.items'),'insurer':F('Seguradora',required=True),'policy':F('Apólice',required=True),'type':F('Tipo de seguro',required=True),'start':day('Início da vigência',True),'end':day('Fim da vigência',True),'amount':money('Valor segurado',True)})
 r['maintenance_plans']=R('Planos de manutenção patrimonial',{**base(),'asset':ref('Bem','assets.items'),'type':choice('Manutenção','Preventiva|Corretiva'),'first_due':day('Primeira manutenção',True),'interval_months':F('Periodicidade em meses','integer',True),'description':text('Procedimentos',True)})
 r['maintenance_records']=R('Manutenções realizadas',{**base(),'plan':ref('Plano de manutenção','assets.maintenance_plans'),'date':day('Realização',True),'supplier':ref('Prestador','procurement.suppliers'),'amount':money('Custo',True),'warranty_through':day('Garantia até'),'report':text('Serviços realizados',True)},operations=['complete_asset_maintenance'])
 r['loans']=R('Comodatos e locações',{**base(),'asset':ref('Bem','assets.items'),'type':choice('Operação','Cessão em comodato|Recebimento em comodato|Recebimento em locação'),'party':F('Cedente / cessionário / locador',required=True),'document':F('CPF / CNPJ da contraparte','document',True),'start':day('Início',True),'end':day('Término previsto',True),'legal_basis':text('Contrato e fundamento',True)},operations=['start_asset_loan','return_asset_loan'])
 r['inventories']['fields'].update(type=choice('Tipo','Anual|Eventual|Transferência de responsabilidade',False),commission_ref=ref('Comissão formalizada','assets.commissions',False),class_filter=ref('Classificação','assets.classes',False),description_filter=F('Descrição contém'),condition_filter=choice('Estado de conservação','Ótimo|Bom|Regular|Ruim',False),situation_filter=choice('Situação de uso','Em uso|Em reserva|Em manutenção|Inservível',False))
 r['inventory_items']=R('Conferência de inventário',{**base(),'inventory':ref('Inventário','assets.inventories'),'asset':ref('Bem','assets.items'),'date':day('Data da conferência',True),'location':F('Localização encontrada',required=True),'responsible':ref('Responsável encontrado','assets.responsibles',False),'condition':choice('Estado encontrado','Ótimo|Bom|Regular|Ruim'),'situation':choice('Situação encontrada','Em uso|Em reserva|Em manutenção|Inservível'),'conformity':text('Registro de conformidade',True),'writeoff':F('Baixar bem na conferência','boolean'),'writeoff_type':F('Tipo da baixa'),'legal_basis':text('Fundamento legal da baixa')},operations=['confirm_inventory_asset'])
 r['entity_transfers']=R('Transferências entre unidades gestoras',{**base(),'asset':ref('Bem de origem','assets.items'),'type':choice('Transferência','Doação|Temporária'),'date':day('Transferência',True),'destination_entity':F('Código interno da entidade de destino','integer',True),'destination_class':F('Código interno da classificação no destino','integer'),'destination_location':F('Local de destino',required=True),'destination_owner':F('Responsável no destino',required=True),'expected_return':day('Retorno previsto'),'legal_basis':text('Fundamento legal',True)},operations=['transfer_asset_entity','return_asset_entity'])
 C['assets']['description']='Ingresso, guarda, inventário, depreciação, avaliação e eventos patrimoniais com reflexo contábil.'

LABELS={'activate_asset':'Efetivar ingresso','confirm_asset_receipt':'Conferir recebimento','reclassify_asset':'Alterar classificação','revise_asset_identity':'Atualizar identificação e situação','reverse_asset_event':'Estornar último evento','seal_asset_commission':'Formalizar comissão patrimonial','approve_asset_rule':'Aprovar regra patrimonial','retire_asset_rule':'Encerrar regra patrimonial','apply_asset_valuation':'Aplicar avaliação','apply_asset_complement':'Incorporar valor complementar','complete_asset_maintenance':'Concluir manutenção','start_asset_loan':'Registrar comodato / locação','return_asset_loan':'Devolver comodato / locação','confirm_inventory_asset':'Conferir item inventariado','transfer_asset_entity':'Efetivar transferência entre entidades','return_asset_entity':'Retornar transferência temporária'}
