LESSONS=[
 {'id':'primeiros-passos','title':'Primeiros passos','category':'Essencial','minutes':8,'description':'Conheça o ambiente e organize sua rotina.','steps':['Entre com sua conta individual. Nunca compartilhe sua senha.','Use o menu para alternar os módulos autorizados pelo seu perfil.','O seletor no cabeçalho alterna os temas claro e escuro. A preferência fica salva neste navegador.','A busca de cada módulo encontra títulos, unidades e detalhes. Combine com filtros de situação.','O botão Ajuda apresenta orientações da tela em que você está.']},
 {'id':'planejamento','title':'Programas, ações e resultados','category':'Planejamento','minutes':15,'description':'Organize ações e acompanhe metas e indicadores.','steps':['Abra Planejamento e orçamento e selecione Nova ação.','Informe programa, ação, exercício, unidade e valor previsto.','Registre uma meta física mensurável, o indicador e o prazo.','Quando a dupla custódia estiver habilitada, aguarde um segundo usuário aprovar a inclusão.','Atualize situação e indicadores para apoiar a avaliação dos resultados. O cadastro é uma base de planejamento; consulte Módulos integrados e a matriz do Anexo III para conhecer a cobertura atual.']},
 {'id':'aprovacoes','title':'Dupla custódia na prática','category':'Segurança','minutes':10,'description':'Revise alterações com uma segunda pessoa.','steps':['Operações protegidas são encaminhadas para Aprovações antes de alterar a base.','O aprovador deve ser outro usuário com permissão no módulo.','Confira a operação e todos os valores na solicitação.','Registre a justificativa e aprove ou rejeite.','Uma solicitação desatualizada não pode sobrescrever um registro modificado. Peça uma nova solicitação.']},
 {'id':'relatorios','title':'Consultas e relatórios','category':'Gestão','minutes':12,'description':'Transforme os registros em informações para decidir.','steps':['Abra Relatórios e selecione o módulo e o período de criação dos registros.','Confira a prévia em tela. Os resultados respeitam suas permissões.','Exporte em PDF, planilha, CSV ou documento.','Na impressão do navegador, escolha a impressora, as páginas e a quantidade de cópias.','Compare valores, metas e situação das ações para identificar desvios. Exportações que exigem assinatura ficam bloqueadas até a integração do certificado.']},
 {'id':'atendimento','title':'Chamados e prazos de atendimento','category':'Suporte','minutes':10,'description':'Registre ocorrências e acompanhe a solução.','steps':['Na Central de atendimento, descreva a ocorrência, a unidade e a prioridade.','Crítico: resposta em 2 horas e solução em 6 horas corridas. Alto: resposta em 4 horas corridas e solução em 8 horas úteis.','Médio: 8 horas úteis para resposta e 24 para solução. Baixo: 24 e 48 horas úteis.','O calendário considera segunda a sexta das 8h às 17h de Brasília, descontando os feriados cadastrados.','Registre mensagens e soluções provisórias. Para resolver, descreva a solução definitiva. As atualizações geram notificações internas.']},
 {'id':'backup','title':'Backup e recuperação','category':'Segurança','minutes':15,'description':'Proteja os registros e verifique a recuperação.','steps':['Com permissão administrativa, abra Administração técnica.','Gere um backup criptografado e baixe o arquivo. A chave fica no diretório privado data.','Guarde cópia da chave em um cofre separado, acessível apenas aos responsáveis. Sem a chave, o backup não pode ser recuperado.','Agende diariamente o comando python manage.py backup usando o agendador institucional.','Restauração: interrompa o serviço e use python manage.py restore CAMINHO. Valide a integridade e teste os fluxos antes de liberar o acesso.']},
 {'id':'acessos','title':'Usuários, grupos e auditoria','category':'Segurança','minutes':15,'description':'Controle o acesso e consulte o histórico.','steps':['Crie grupos com permissões de consultar, gravar, excluir e aprovar por módulo.','Crie contas individuais, defina a unidade e exija troca de senha no primeiro acesso.','Horários de acesso são avaliados pelo servidor no fuso de Brasília.','Permissões individuais substituem as do grupo apenas nos módulos informados.','A Auditoria registra acessos e alterações. As entradas não podem ser modificadas ou excluídas pela aplicação.']},
 {'id':'implantacao','title':'Implantação e homologação','category':'Gestão','minutes':12,'description':'Acompanhe marcos, ordens de serviço e evidências.','steps':['Cadastre a data do contrato em Configurações e registre as ordens de serviço.','Planeje a disponibilização dos módulos prioritários em 30 dias e a implantação em até 90 dias, conforme o documento.','Registre responsáveis, prazos, impedimentos e aceite das unidades.','Consulte a matriz do edital para separar funcionalidades, obrigações operacionais e dependências externas.','O Anexo III foi catalogado. Consulte sua matriz para distinguir rotinas implementadas, parciais e pendentes. A homologação depende da solução completa, infraestrutura e testes de cada módulo.']},
]
