"""Catálogo tipado de cadastros e operações do núcleo integrado."""
def F(label,kind='text',required=False,**kw):
 return {'label':label,'type':kind,'required':required,**kw}
def R(label,fields,**kw):return {'label':label,'fields':fields,**kw}
def ref(label,target,required=True):return F(label,'reference',required,reference=target)
def choice(label,options,required=True):return F(label,'select',required,options=options.split('|'))
def moneyf(label,required=False):return F(label,'money',required)
def datef(label,required=False):return F(label,'date',required)
def qty(label,required=False):return F(label,'quantity',required)
def text(label,required=False):return F(label,'textarea',required)

CATALOG={
 'finance':{'label':'Execução financeira','icon':'wallet','description':'Dotações, empenhos, liquidações, pagamentos e partidas dobradas.','resources':{
  'accounts':R('Plano de contas',{'code':F('Código da conta',required=True),'name':F('Descrição',required=True),'nature':choice('Natureza','Devedora|Credora'),'analytic':F('Conta analítica','boolean'),'active':F('Ativa','boolean')}),
  'funds':R('Fontes de recursos',{'code':F('Código',required=True),'name':F('Descrição',required=True),'msc_code':F('Relacionamento MSC')}),
  'plans':R('Peças de planejamento',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'type':choice('Peça','PPA|LDO|LOA'),'start_year':F('Exercício inicial','integer',True),'end_year':F('Exercício final','integer',True),'legal_act':F('Ato legal'),'approved':F('Aprovada','boolean')}),
  'programs':R('Programas e indicadores',{'code':F('Código',required=True),'name':F('Programa',required=True),'plan':ref('Peça de planejamento','finance.plans'),'objective':text('Objetivo',True),'problem':text('Problema'),'audience':text('Público-alvo'),'indicator':F('Indicador',required=True),'current_index':qty('Índice atual'),'target_index':qty('Índice previsto'),'measurement_date':datef('Data de apuração'),'periodicity':choice('Periodicidade','Mensal|Bimestral|Trimestral|Semestral|Anual')}),
  'appropriations':R('Dotações orçamentárias',{'code':F('Dotação',required=True),'name':F('Descrição',required=True),'program':ref('Programa','finance.programs',False),'fund':ref('Fonte','finance.funds'),'function':F('Função'),'subfunction':F('Subfunção'),'expense_nature':F('Natureza da despesa',required=True),'initial':moneyf('Dotação inicial',True)},operations=['supplement','reduce']),
  'commitments':R('Empenhos',{'code':F('Número',required=True),'name':F('Histórico',required=True),'appropriation':ref('Dotação','finance.appropriations'),'supplier':ref('Credor','procurement.suppliers'),'date':datef('Emissão',True),'amount':moneyf('Valor',True),'type':choice('Tipo','Ordinário|Global|Estimativo')},operations=['commit','cancel_commitment']),
  'settlements':R('Liquidações',{'code':F('Número',required=True),'name':F('Histórico',required=True),'commitment':ref('Empenho','finance.commitments'),'date':datef('Liquidação',True),'invoice':F('Documento fiscal',required=True),'amount':moneyf('Valor',True)},operations=['settle']),
  'payments':R('Pagamentos',{'code':F('Número',required=True),'name':F('Histórico',required=True),'settlement':ref('Liquidação','finance.settlements'),'bank':ref('Conta bancária','finance.bank_accounts'),'date':datef('Pagamento',True),'amount':moneyf('Valor',True)},operations=['pay']),
  'bank_accounts':R('Contas bancárias',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'bank_code':F('Banco',required=True),'branch':F('Agência',required=True),'number':F('Conta',required=True),'fund':ref('Fonte','finance.funds'),'ledger_account':ref('Conta contábil','finance.accounts'),'opening':moneyf('Saldo de implantação')}),
  'receipts':R('Arrecadações',{'code':F('Número',required=True),'name':F('Histórico',required=True),'bank':ref('Conta bancária','finance.bank_accounts'),'fund':ref('Fonte','finance.funds'),'revenue_nature':F('Natureza de receita',required=True),'date':datef('Arrecadação',True),'amount':moneyf('Valor bruto',True),'deduction':moneyf('Dedução')},operations=['receive']),
  'journals':R('Lançamentos contábeis',{'code':F('Número',required=True),'name':F('Histórico',required=True),'date':datef('Movimento',True),'debit':ref('Conta a débito','finance.accounts'),'credit':ref('Conta a crédito','finance.accounts'),'fund':ref('Fonte','finance.funds'),'amount':moneyf('Valor',True)},operations=['post_journal','reverse_journal']),
  'locks':R('Fechamento de períodos',{'code':F('Identificação',required=True),'name':F('Motivo',required=True),'through':datef('Bloquear movimentos até',True)},operations=['lock_period']),
 }},
 'control':{'label':'Controle interno','icon':'shield','description':'Obrigações, ocorrências, planos de ação e versões de pareceres.','resources':{
  'obligations':R('Obrigações',{'code':F('Código',required=True),'name':F('Título',required=True),'description':text('Descrição legal',True),'legislation':F('Legislação',required=True),'level':choice('Esfera','Federal|Estadual|Municipal'),'subject':F('Grupo de assunto'),'delivery':F('Forma de envio'),'destination':F('Destinatário'),'url':F('Fonte da obrigação','url'),'owner':F('Responsável',required=True),'first_due':datef('Primeiro vencimento',True),'interval_months':F('Intervalo em meses','integer',True),'occurrences':F('Quantidade de ocorrências','integer',True)},operations=['generate_occurrences']),
  'occurrences':R('Ocorrências',{'code':F('Identificação',required=True),'name':F('Título',required=True),'obligation':ref('Obrigação','control.obligations'),'due_date':datef('Vencimento',True),'owner':F('Responsável',required=True),'justification':text('Justificativa')},operations=['close_occurrence','reopen_occurrence']),
  'findings':R('Verificações e planos de ação',{'code':F('Identificação',required=True),'name':F('Verificação',required=True),'source':choice('Origem','Interna|SICONFI|CAUC|Convênios'),'dimension':F('Dimensão'),'period':F('Competência','month',True),'compliant':F('Em conformidade','boolean'),'fact':text('Fato',True),'cause':text('Causa'),'action':text('Ação corretiva'),'owner':F('Responsável',required=True),'due_date':datef('Prazo')}),
  'reports':R('Pareceres conclusivos',{'code':F('Número',required=True),'name':F('Título',required=True),'period':F('Competência','month',True),'opinion':text('Parecer',True),'conclusion':text('Considerações finais',True),'signatory':F('Responsável pelo parecer',required=True)},operations=['seal_report']),
  'agreements':R('Convênios',{'code':F('Número',required=True),'name':F('Objeto',required=True),'grantor':F('Concedente',required=True),'amount':moneyf('Valor',True),'counterpart':moneyf('Contrapartida'),'start':datef('Início',True),'end':datef('Fim',True),'owner':F('Responsável')}),
 }},
 'people':{'label':'Gestão de pessoas','icon':'users','description':'Servidores, cargos, vínculos, afastamentos e cálculo parametrizado.','resources':{
  'positions':R('Cargos e vagas',{'code':F('Código',required=True),'name':F('Cargo',required=True),'vacancies':F('Vagas autorizadas','integer',True),'salary':moneyf('Vencimento base',True),'hours':qty('Carga horária semanal',True)}),
  'employees':R('Servidores e vínculos',{'code':F('Matrícula',required=True),'name':F('Nome completo',required=True),'cpf':F('CPF','cpf',True),'position':ref('Cargo','people.positions'),'department':F('Lotação',required=True),'cost_center':F('Centro de custo'),'admission':datef('Admissão',True),'regime':choice('Regime previdenciário','RPPS|RGPS'),'salary':moneyf('Salário contratual',True),'active':F('Vínculo ativo','boolean'),'email':F('E-mail','email')}),
  'dependents':R('Dependentes',{'code':F('Identificação',required=True),'name':F('Nome',required=True),'employee':ref('Servidor','people.employees'),'cpf':F('CPF','cpf'),'birth':datef('Nascimento',True),'relationship':choice('Parentesco','Filho(a)|Cônjuge|Companheiro(a)|Outro'),'income_tax':F('Dependente para IRRF','boolean')}),
  'events':R('Verbas e movimentos',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'employee':ref('Servidor','people.employees'),'period':F('Competência','month',True),'type':choice('Tipo','Provento|Desconto|Consignação'),'amount':moneyf('Valor',True),'pension_base':F('Compõe base previdenciária','boolean'),'tax_base':F('Compõe base de IRRF','boolean'),'priority':F('Prioridade da consignação','integer')}),
  'rules':R('Parâmetros de cálculo',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'period':F('Competência','month',True),'pension_rate':F('RPPS do servidor (%)','percent',True),'employer_rate':F('RPPS patronal (%)','percent',True),'supplementary_rate':F('Contribuição suplementar (%)','percent'),'margin':F('Margem consignável (%)','percent',True),'dependent_deduction':moneyf('Dedução por dependente'),'legal_basis':text('Fundamentação / ato aprovado',True)},operations=['approve_rules']),
  'tax_bands':R('Faixas de IRRF',{'code':F('Código',required=True),'name':F('Descrição',required=True),'rules':ref('Parâmetros','people.rules'),'lower':moneyf('Limite inferior',True),'upper':moneyf('Limite superior (zero = sem teto)'),'rate':F('Alíquota (%)','percent',True),'deduction':moneyf('Parcela a deduzir')}),
  'runs':R('Folhas e conferência',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'period':F('Competência','month',True),'rules':ref('Parâmetros','people.rules')},operations=['calculate_payroll','approve_payroll']),
  'leaves':R('Férias e afastamentos',{'code':F('Identificação',required=True),'name':F('Motivo',required=True),'employee':ref('Servidor','people.employees'),'type':choice('Tipo','Férias|Licença|Maternidade|Afastamento|Cessão'),'start':datef('Início',True),'end':datef('Fim',True),'legal_act':F('Ato administrativo')}),
 }},
 'procurement':{'label':'Compras e contratos','icon':'file','description':'Fornecedores, fases de contratação, propostas, contratos e aditivos.','resources':{
  'suppliers':R('Fornecedores',{'code':F('Código',required=True),'name':F('Razão social',required=True),'document':F('CPF / CNPJ','document',True),'email':F('E-mail','email'),'phone':F('Telefone'),'address':text('Endereço'),'blocked_from':datef('Impedimento desde'),'blocked_until':datef('Impedimento até'),'block_reason':text('Tipo / motivo do impedimento')}),
  'processes':R('Processos de contratação',{'code':F('Número / ano',required=True),'name':F('Objeto',required=True),'modality':choice('Modalidade','Pregão|Concorrência|Concurso|Leilão|Dispensa|Inexigibilidade|Credenciamento|Chamada pública'),'judgment':choice('Critério','Menor preço|Maior desconto'),'legal_basis':F('Legislação adotada',required=True),'publication':datef('Publicação'),'opening':datef('Abertura'),'business_days':F('Prazo em dias úteis','integer'),'estimated':moneyf('Valor estimado'),'technical_opinion':text('Parecer técnico'),'legal_opinion':text('Parecer jurídico'),'inverted':F('Habilitação antes do julgamento','boolean'),'consortium':F('Permite consórcio','boolean')},operations=['advance_process','calculate_opening','generate_price_agreement','register_carona']),
  'items':R('Itens da contratação',{'code':F('Número do item',required=True),'name':F('Descrição',required=True),'process':ref('Processo','procurement.processes'),'unit':F('Unidade',required=True),'quantity':qty('Quantidade',True),'unit_price':moneyf('Preço estimado',True),'lot':F('Lote'),'manufacturer':F('Fabricante'),'barcode':F('Código de barras')}),
  'proposals':R('Propostas e cotações',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'item':ref('Item','procurement.items'),'supplier':ref('Fornecedor','procurement.suppliers'),'unit_price':moneyf('Preço ofertado',True),'discount':F('Desconto (%)','percent'),'qualified':F('Fornecedor habilitado','boolean')},operations=['award_proposal']),
  'contracts':R('Contratos',{'code':F('Número',required=True),'name':F('Objeto',required=True),'process':ref('Processo','procurement.processes'),'supplier':ref('Fornecedor','procurement.suppliers'),'start':datef('Início',True),'end':datef('Fim',True),'amount':moneyf('Valor inicial',True),'manager':F('Gestor',required=True),'inspector':F('Fiscal',required=True)},operations=['activate_contract']),
  'amendments':R('Aditivos',{'code':F('Número',required=True),'name':F('Objeto',required=True),'contract':ref('Contrato','procurement.contracts'),'type':choice('Tipo','Acréscimo|Supressão|Prazo'),'amount':moneyf('Valor'),'end':datef('Novo término'),'justification':text('Justificativa',True),'legal_opinion':text('Parecer jurídico',True)},operations=['apply_amendment']),
  'pca':R('Plano de contratação anual',{'code':F('Código',required=True),'name':F('Objeto',required=True),'department':F('Unidade requisitante',required=True),'quantity':qty('Quantidade',True),'estimated':moneyf('Valor estimado',True),'priority':choice('Prioridade','Baixa|Média|Alta'),'due_date':datef('Data prevista'),'justification':text('Justificativa')},operations=['copy_pca','approve_pca','reject_pca','publish_pca_pncp']),
 }},
 'inventory':{'label':'Gestão de estoque','icon':'database','description':'Materiais, entradas, saídas, transferências em trânsito e inventário.','resources':{
  'warehouses':R('Almoxarifados',{'code':F('Código',required=True),'name':F('Nome',required=True),'location':F('Localização',required=True),'owner':F('Responsável',required=True),'blocked':F('Bloquear movimentações','boolean')}),
  'materials':R('Materiais',{'code':F('Código',required=True),'name':F('Descrição',required=True),'unit':F('Unidade',required=True),'group':F('Grupo'),'subgroup':F('Subgrupo'),'minimum':qty('Estoque mínimo'),'maximum':qty('Estoque máximo'),'ncm':F('NCM'),'nbs':F('NBS'),'expiry_control':F('Controlar validade','boolean'),'obsolete':F('Material obsoleto','boolean')}),
  'movements':R('Movimentações',{'code':F('Documento',required=True),'name':F('Histórico',required=True),'warehouse':ref('Almoxarifado','inventory.warehouses'),'material':ref('Material','inventory.materials'),'type':choice('Movimento','Entrada|Saída|Transferência|Devolução'),'destination':ref('Almoxarifado de destino','inventory.warehouses',False),'date':datef('Movimento',True),'quantity':qty('Quantidade',True),'unit_price':moneyf('Valor unitário'),'batch':F('Lote'),'expiry':datef('Validade'),'invoice':F('Nota fiscal / série'),'supplier':ref('Fornecedor','procurement.suppliers',False)},operations=['execute_stock','receive_transfer']),
  'counts':R('Inventários',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'warehouse':ref('Almoxarifado','inventory.warehouses'),'material':ref('Material','inventory.materials'),'quantity':qty('Quantidade contada',True),'date':datef('Data',True),'ordinance':F('Portaria',required=True),'commission':text('Membros / CPF / cargo da comissão',True)},operations=['adjust_stock']),
 }},
 'assets':{'label':'Patrimônio','icon':'building','description':'Bens, classificações, inventário e depreciação com histórico.','resources':{
  'classes':R('Classificações patrimoniais',{'code':F('Código',required=True),'name':F('Descrição',required=True),'asset_account':ref('Conta de ativo imobilizado','finance.accounts'),'depreciation_account':ref('Depreciação acumulada','finance.accounts'),'useful_months':F('Vida útil (meses)','integer',True),'residual_percent':F('Residual (%)','percent',True)}),
  'items':R('Bens',{'code':F('Placa patrimonial',required=True),'name':F('Descrição',required=True),'class':ref('Classificação','assets.classes'),'type':choice('Tipo','Próprio|Alugado|Comodato'),'location':F('Localização',required=True),'owner':F('Responsável',required=True),'owner_cpf':F('CPF do responsável','cpf'),'condition':choice('Conservação','Ótimo|Bom|Regular|Ruim'),'date':datef('Ingresso',True),'amount':moneyf('Valor de ingresso',True),'method':choice('Depreciação','Quotas constantes|Unidades produzidas|Não depreciável'),'start':datef('Início da depreciação',True),'total_units':qty('Produção total estimada'),'supplier':ref('Fornecedor','procurement.suppliers',False)},operations=['depreciate','transfer_asset','writeoff_asset']),
  'inventories':R('Inventários patrimoniais',{'code':F('Número',required=True),'name':F('Descrição',required=True),'location':F('Localização',required=True),'date':datef('Abertura',True),'commission':text('Comissão / portaria',True)},operations=['open_inventory','close_inventory']),
 }},
 'fleet':{'label':'Gestão de frotas','icon':'truck','description':'Veículos vinculados ao patrimônio, deslocamentos e consumo.','resources':{
  'drivers':R('Motoristas',{'code':F('Matrícula',required=True),'name':F('Nome',required=True),'cpf':F('CPF','cpf',True),'license':F('CNH',required=True),'category':choice('Categoria','A|B|AB|C|D|E|AC|AD|AE'),'expiry':datef('Validade da CNH',True),'phone':F('Telefone'),'address':text('Endereço')}),
  'vehicles':R('Veículos e equipamentos',{'code':F('Placa / identificação',required=True),'name':F('Descrição',required=True),'asset':ref('Bem patrimonial','assets.items'),'fuel':choice('Combustível','Gasolina|Etanol|Flex|Diesel|Elétrico'),'meter_type':choice('Medidor','Hodômetro|Horímetro'),'opening_meter':qty('Leitura inicial',True),'tank_capacity':qty('Capacidade do tanque'),'consumption_limit':qty('Consumo de referência'),'blocked_through':datef('Bloquear movimentos até')},operations=['change_plate']),
  'trips':R('Deslocamentos',{'code':F('Identificação',required=True),'name':F('Finalidade',required=True),'vehicle':ref('Veículo','fleet.vehicles'),'driver':ref('Motorista','fleet.drivers'),'departure':F('Saída','datetime',True),'return':F('Retorno','datetime',True),'start_meter':qty('Leitura na saída',True),'end_meter':qty('Leitura no retorno',True),'requester':F('Solicitante',required=True),'route':text('Roteiro',True)},operations=['register_trip']),
  'refuels':R('Abastecimentos',{'code':F('Documento',required=True),'name':F('Descrição',required=True),'vehicle':ref('Veículo','fleet.vehicles'),'driver':ref('Motorista','fleet.drivers'),'date':F('Data e hora','datetime',True),'meter':qty('Leitura',True),'fuel':choice('Combustível','Gasolina|Etanol|Diesel'),'liters':qty('Litros',True),'unit_price':moneyf('Preço por litro',True),'station':choice('Posto','Próprio|Terceiro'),'invoice':F('Nota fiscal')},operations=['register_refuel']),
  'reservations':R('Reservas',{'code':F('Identificação',required=True),'name':F('Finalidade',required=True),'vehicle':ref('Veículo','fleet.vehicles'),'driver':ref('Motorista','fleet.drivers'),'start':F('Início','datetime',True),'end':F('Fim','datetime',True),'requester':F('Solicitante',required=True)}),
  'services':R('Manutenções',{'code':F('Ordem de serviço',required=True),'name':F('Serviço',required=True),'vehicle':ref('Veículo','fleet.vehicles'),'date':datef('Data prevista',True),'meter':qty('Leitura prevista'),'amount':moneyf('Custo',True),'type':choice('Tipo','Preventiva|Corretiva|Óleo|Seguro|Imposto')},operations=['close_service']),
 }},
 'social':{'label':'Assistência social','icon':'heart','description':'Famílias, prontuários, benefícios e acompanhamento com acesso restrito.','resources':{
  'persons':R('Pessoas',{'code':F('Identificação / NIS',required=True),'name':F('Nome completo',required=True),'cpf':F('CPF','cpf'),'birth':datef('Nascimento',True),'mother':F('Nome da mãe'),'address':text('Endereço',True),'phone':F('Telefone'),'income':moneyf('Renda mensal'),'disability':F('Pessoa com deficiência','boolean'),'special_needs':text('Necessidades específicas')}),
  'families':R('Famílias',{'code':F('Código familiar',required=True),'name':F('Identificação',required=True),'responsible':ref('Responsável familiar','social.persons'),'address':text('Endereço',True),'territory':F('Território'),'housing':choice('Moradia','Própria|Alugada|Cedida|Situação de rua|Outra')}),
  'members':R('Composição familiar',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'family':ref('Família','social.families'),'person':ref('Pessoa','social.persons'),'relationship':F('Parentesco',required=True)}),
  'programs':R('Programas sociais',{'code':F('Código',required=True),'name':F('Nome',required=True),'type':choice('Tipo','PAIF|PAEFI|SCFV|Habitacional|Outro'),'description':text('Descrição')}),
  'appointments':R('Agendamentos',{'code':F('Identificação',required=True),'name':F('Motivo',required=True),'person':ref('Pessoa','social.persons'),'professional':F('Profissional',required=True),'unit':F('Unidade',required=True),'start':F('Início','datetime',True),'end':F('Fim','datetime',True)},operations=['attend_appointment','cancel_appointment']),
  'visits':R('Atendimentos e prontuários',{'code':F('Identificação',required=True),'name':F('Motivo',required=True),'person':ref('Pessoa','social.persons'),'family':ref('Família','social.families',False),'program':ref('Programa','social.programs',False),'date':datef('Atendimento',True),'professional':F('Profissional',required=True),'specialty':F('Especialidade',required=True),'unit':F('Unidade',required=True),'notes':text('Registro técnico',True),'referral':text('Encaminhamentos'),'confidential':F('Informação sigilosa','boolean')}),
  'benefits':R('Benefícios',{'code':F('Código',required=True),'name':F('Descrição',required=True),'amount':moneyf('Valor unitário',True),'interval_days':F('Intervalo mínimo (dias)','integer'),'capacity':F('Limite de concessões (zero = sem limite)','integer'),'material':ref('Insumo do benefício','inventory.materials',False),'units':qty('Quantidade do insumo por concessão')}),
  'concessions':R('Concessões',{'code':F('Identificação',required=True),'name':F('Justificativa',required=True),'person':ref('Beneficiário','social.persons'),'benefit':ref('Benefício','social.benefits'),'date':datef('Data',True),'professional':F('Responsável',required=True),'warehouse':ref('Almoxarifado de entrega','inventory.warehouses',False)},operations=['grant_benefit']),
  'housing':R('Inscrições habitacionais',{'code':F('Inscrição',required=True),'name':F('Descrição',required=True),'family':ref('Família','social.families'),'program':ref('Programa','social.programs'),'date':datef('Inscrição',True),'priority':F('Grupo de priorização'),'justification':text('Justificativa da classificação')}),
  'organizations':R('Organizações da sociedade civil',{'code':F('Código',required=True),'name':F('Razão social',required=True),'cnpj':F('CNPJ','cnpj',True),'address':text('Endereço',True),'representative':F('Representante',required=True)}),
  'plans':R('Planos de trabalho OSC',{'code':F('Número',required=True),'name':F('Objeto',required=True),'organization':ref('OSC','social.organizations'),'start':datef('Início',True),'end':datef('Fim',True),'amount':moneyf('Valor pactuado',True),'goals':text('Metas',True)}),
  'accounts':R('Prestação de contas OSC',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'plan':ref('Plano de trabalho','social.plans'),'period':F('Competência','month',True),'opening':moneyf('Saldo anterior'),'transfers':moneyf('Repasses públicos'),'interest':moneyf('Rendimentos'),'counterpart':moneyf('Contrapartida'),'expenses':moneyf('Despesas comprovadas'),'opinion':text('Parecer técnico')},operations=['review_accounts']),
 }},
 'works':{'label':'Obras públicas','icon':'building','description':'Planilhas, diário, medições sequenciais, pagamentos e retenções.','resources':{
  'projects':R('Obras e projetos',{'code':F('Código',required=True),'name':F('Objeto',required=True),'contract':ref('Contrato','procurement.contracts',False),'supplier':ref('Contratada','procurement.suppliers'),'engineer':F('Responsável técnico',required=True),'registration':F('CREA / CAU',required=True),'address':text('Localização',True),'latitude':F('Latitude','decimal'),'longitude':F('Longitude','decimal'),'start':datef('Início',True),'end':datef('Fim previsto',True),'retention_days':F('Prazo de liberação das retenções (dias)','integer'),'completed_date':datef('Recebimento definitivo'),'public':F('Publicar informações gerais','boolean')},operations=['close_project']),
  'items':R('Planilha contratual',{'code':F('Item',required=True),'name':F('Serviço',required=True),'project':ref('Obra','works.projects'),'unit':F('Unidade',required=True),'quantity':qty('Quantidade contratada',True),'unit_price':moneyf('Preço unitário',True),'bdi':F('BDI (%)','percent'),'discount':F('Desconto (%)','percent'),'start':datef('Início da etapa',True),'end':datef('Fim da etapa',True)}),
  'diaries':R('Diários de obra',{'code':F('Número',required=True),'name':F('Descrição',required=True),'project':ref('Obra','works.projects'),'date':datef('Dia',True),'weather':choice('Condições','Bom|Chuva|Imprevisto'),'worked':choice('Jornada','Integral|Meio período|Não trabalhado'),'activities':text('Atividades',True),'equipment':text('Equipamentos'),'workforce':text('Mão de obra'),'occurrences':text('Ocorrências')},operations=['approve_diary']),
  'measurements':R('Medições',{'code':F('Número',required=True),'name':F('Descrição',required=True),'project':ref('Obra','works.projects'),'item':ref('Item da planilha','works.items'),'start':datef('Período inicial',True),'end':datef('Período final',True),'quantity':qty('Quantidade executada',True)},operations=['submit_measurement','approve_measurement']),
  'payments':R('Pagamentos e retenções',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'measurement':ref('Medição aprovada','works.measurements'),'date':datef('Pagamento',True),'amount':moneyf('Valor pago',True),'type':choice('Pagamento','Medição|Retenção')},operations=['pay_measurement']),
 }},
 'auction':{'label':'Pregão eletrônico','icon':'globe','description':'Pacotes de intercâmbio e rastreabilidade com plataformas externas.','resources':{
  'exchanges':R('Intercâmbios',{'code':F('Identificação',required=True),'name':F('Descrição',required=True),'process':ref('Processo','procurement.processes'),'provider':choice('Plataforma','BLL|PCP|BNC|Compras BR|AMM Licita|Licitar Digital|LicitaNet|BBMNET|Brconectado'),'external_id':F('Identificador externo'),'notes':text('Observações')},operations=['prepare_exchange']),
 }},
 'bi':{'label':'Painel do gestor · BI','icon':'chart','description':'Indicadores calculados sobre os registros efetivados.','resources':{}},
}
from inventory_catalog import register as register_inventory, LABELS as INVENTORY_LABELS
register_inventory(CATALOG,F,R,ref,choice,moneyf,datef,qty,text)
from asset_catalog import register as register_assets, LABELS as ASSET_LABELS
register_assets(CATALOG,F,R,ref,choice,moneyf,datef,qty,text)
from fleet_catalog import register as register_fleet, LABELS as FLEET_LABELS
register_fleet(CATALOG,F,R,ref,choice,moneyf,datef,qty,text)
from works_catalog import register as register_works, LABELS as WORKS_LABELS
register_works(CATALOG,F,R,ref,choice,moneyf,datef,qty,text)
ERP_SCOPES=list(CATALOG)+['entities','social_confidential']
OP_LABELS={'supplement':'Suplementar dotação','reduce':'Reduzir dotação','commit':'Efetivar empenho','cancel_commitment':'Anular empenho','settle':'Liquidar','pay':'Efetivar pagamento','receive':'Arrecadar','post_journal':'Contabilizar','reverse_journal':'Estornar lançamento','lock_period':'Fechar período','generate_occurrences':'Gerar recorrências','close_occurrence':'Encerrar ocorrência','reopen_occurrence':'Reabrir ocorrência','seal_report':'Fechar versão do parecer','approve_rules':'Aprovar parâmetros','calculate_payroll':'Calcular folha','approve_payroll':'Aprovar folha','advance_process':'Avançar fase','calculate_opening':'Calcular abertura','award_proposal':'Adjudicar proposta','activate_contract':'Formalizar contrato','apply_amendment':'Aplicar aditivo','copy_pca':'Copiar para exercício','execute_stock':'Efetivar movimento','receive_transfer':'Receber transferência','adjust_stock':'Ajustar inventário','depreciate':'Calcular depreciação','transfer_asset':'Transferir bem','writeoff_asset':'Baixar bem','open_inventory':'Abrir inventário','close_inventory':'Finalizar inventário','change_plate':'Alterar placa','register_trip':'Registrar deslocamento','register_refuel':'Registrar abastecimento','close_service':'Concluir manutenção','grant_benefit':'Conceder benefício','review_accounts':'Homologar contas','approve_diary':'Aprovar diário','submit_measurement':'Submeter medição','approve_measurement':'Aprovar medição','pay_measurement':'Registrar pagamento','prepare_exchange':'Preparar intercâmbio'}

OP_LABELS.update(INVENTORY_LABELS)
OP_LABELS.update(ASSET_LABELS)
OP_LABELS.update(FLEET_LABELS)
OP_LABELS.update(WORKS_LABELS)
from procurement_catalog import register as register_procurement, LABELS as PROCUREMENT_LABELS
register_procurement(CATALOG,F,R,ref,choice,moneyf,datef,qty,text)
OP_LABELS.update(PROCUREMENT_LABELS)
