"""Cadastros completos de gestão de frota e equipamentos."""
def register(C,F,R,ref,choice,money,day,qty,text):
 r=C['fleet']['resources'];base=lambda:dict(code=F('Código / identificação',required=True),name=F('Descrição',required=True))
 r['vehicle_types']=R('Tipos de veículos e equipamentos',{**base(),'locomotion':choice('Locomoção','Automotora|Tracionada|Fixa'),'running_gear':choice('Rodante','Pneu|Esteira|Não aplicável'),'consumption_measure':choice('Medição de consumo','Quilômetro|Hora')})
 r['drivers']['fields'].update(relationship=choice('Vínculo funcional','Efetivo|Comissionado|Eletivo|Terceirizado|Estagiário'),registration=F('Registro funcional',required=True))
 r['vehicles']['fields'].update(vehicle_type=ref('Tipo de veículo','fleet.vehicle_types'),responsible_driver=ref('Motorista responsável','fleet.drivers',False),renavam=F('RENAVAM'),chassis=F('Chassi'),manufacture_year=F('Ano de fabricação','integer'),model_year=F('Ano do modelo','integer'),model=F('Modelo'),color=F('Cor predominante'),adaptations=text('Adaptações realizadas'),active=F('Ativo','boolean'))
 r['vehicle_insurances']=R('Seguros da frota',{**base(),'vehicle':ref('Veículo','fleet.vehicles'),'insurer':F('Seguradora',required=True),'policy':F('Apólice',required=True),'start':day('Início',True),'end':day('Fim',True),'insured_value':money('Valor segurado',True)})
 r['tanks']=R('Tanques de combustível',{**base(),'location':F('Localização',required=True),'fuel':choice('Combustível','Gasolina|Etanol|Diesel'),'capacity':qty('Capacidade em litros',True),'opening':qty('Saldo inicial em litros',True),'active':F('Ativo','boolean')})
 r['tank_movements']=R('Movimentos de tanques',{**base(),'type':choice('Movimento','Entrada|Transferência'),'date':F('Data e hora','datetime',True),'tank':ref('Tanque de origem / entrada','fleet.tanks'),'destination':ref('Tanque de destino','fleet.tanks',False),'liters':qty('Litros',True),'unit_price':money('Preço por litro'),'supplier':ref('Fornecedor','procurement.suppliers',False),'invoice':F('Nota fiscal')},operations=['execute_tank_movement'])
 r['refuels']['fields'].update(tank=ref('Tanque próprio','fleet.tanks',False),station_document=F('CNPJ do posto','cnpj'),card_reference=F('Identificador no cartão'),import_batch=F('Lote importado','integer'))
 r['fuel_imports']=R('Importações de cartão combustível',{**base(),'period_start':day('Período inicial',True),'period_end':day('Período final',True),'layout':choice('Formato','CSV oficial configurável|CSV padrão'),'file_hash':F('SHA-256 do arquivo'),'rows':F('Linhas importadas','integer')})
 r['expenses']=R('Despesas de veículos e equipamentos',{**base(),'vehicle':ref('Veículo / equipamento','fleet.vehicles'),'date':day('Data',True),'event':F('Evento de origem',required=True),'account':ref('Conta contábil da despesa','finance.accounts'),'amount':money('Valor',True),'commitment':ref('Empenho','finance.commitments',False),'document':F('Documento')},operations=['post_fleet_expense'])
 r['accessories']=R('Itens agregados',{**base(),'vehicle':ref('Veículo','fleet.vehicles'),'type':choice('Tipo','Rádio|Antena|Pneu|Tacógrafo|Extintor|Equipamento|Outro'),'serial':F('Número de série'),'installed':day('Instalação',True),'removed':day('Retirada'),'condition':choice('Conservação','Ótimo|Bom|Regular|Ruim')})
 r['accessory_schedules']=R('Agenda de itens agregados',{**base(),'accessory':ref('Item agregado','fleet.accessories'),'service':F('Serviço previsto',required=True),'due_date':day('Data prevista'),'due_meter':qty('Leitura prevista')})
 r['service_plans']=R('Planos de serviço',{**base(),'description':text('Escopo do plano',True),'interval_days':F('Periodicidade em dias','integer'),'interval_meter':qty('Periodicidade por medidor')})
 r['service_plan_items']=R('Itens dos planos de serviço',{**base(),'plan':ref('Plano','fleet.service_plans'),'service':F('Serviço',required=True),'sequence':F('Sequência','integer',True)})
 r['services']['fields'].update(plan=ref('Plano de serviço','fleet.service_plans',False),opened_at=F('Abertura','datetime'),closed_at=F('Conclusão','datetime'),driver=ref('Motorista responsável','fleet.drivers',False),supplier=ref('Prestador','procurement.suppliers',False),location=F('Local de execução'),invoice=F('Nota fiscal'))
 r['service_lines']=R('Itens das ordens de serviço',{**base(),'service_order':ref('Ordem de serviço','fleet.services'),'plan_item':ref('Item do plano','fleet.service_plan_items',False),'material':ref('Material de estoque','inventory.materials',False),'warehouse':ref('Almoxarifado','inventory.warehouses',False),'quantity':qty('Quantidade',True),'unit_cost':money('Custo unitário',True)})
 r['oil_changes']=R('Trocas de óleo',{**base(),'vehicle':ref('Veículo','fleet.vehicles'),'driver':ref('Motorista','fleet.drivers'),'date':F('Data e hora','datetime',True),'meter':qty('Leitura',True),'location_type':choice('Execução','Dependência própria|Terceiro'),'liters':qty('Quantidade de óleo',True),'invoice':F('Nota fiscal'),'amount':money('Valor')},operations=['register_oil_change'])
 r['agendas']=R('Agenda da frota',{**base(),'vehicle':ref('Veículo','fleet.vehicles'),'type':choice('Compromisso','Plano de manutenção|Revisão periódica|Recarga de extintor|Renovação de seguro|Imposto|Outro'),'due_date':day('Data prevista'),'due_meter':qty('Leitura prevista'),'notes':text('Observações')})
 r['infractions']=R('Infrações de trânsito',{**base(),'trip':ref('Movimento de trânsito','fleet.trips'),'notifying_agency':F('Órgão notificador',required=True),'notification':F('Número da notificação',required=True),'crv_bo':F('CRV / BO (DNIT)'),'date':day('Data da infração',True),'infraction_number':F('Código da infração',required=True),'points':F('Pontuação','integer',True),'amount':money('Valor',True),'discount_amount':money('Valor com desconto'),'commitment':ref('Empenho do pagamento','finance.commitments',False)})
 r['accidents']=R('Acidentes e ocorrências',{**base(),'trip':ref('Movimento de trânsito','fleet.trips'),'date':F('Data e hora','datetime',True),'location':F('Local',required=True),'report':text('Relato da ocorrência',True),'police_report':F('Boletim de ocorrência')})
 C['fleet']['description']='Veículos, máquinas, equipamentos, motoristas, combustível, custos, agendas e ocorrências integrados ao patrimônio.'

LABELS={'execute_tank_movement':'Efetivar movimento do tanque','post_fleet_expense':'Registrar despesa da frota','register_oil_change':'Registrar troca de óleo'}
