"""Cadastros e operações do ciclo de requisição, aquisição e consumo de materiais."""
def register(C,F,R,ref,choice,money,day,qty,text):
 r=C['inventory']['resources']
 base=lambda:dict(code=F('Código',required=True),name=F('Descrição',required=True))
 r['departments']=R('Órgãos requisitantes',{**base(),'group':F('Grupo',required=True),'subgroup':F('Subgrupo'),'owner':F('Responsável',required=True),'active':F('Ativo','boolean'),'restricted':F('Exigir autorização individual para requisitar','boolean')})
 r['cost_centers']=R('Centros de custo',{**base(),'parent':ref('Centro superior','inventory.cost_centers',False),'department':ref('Órgão requisitante','inventory.departments'),'owner':F('Responsável',required=True)})
 r['locations']=R('Localização dos materiais',{**base(),'warehouse':ref('Almoxarifado','inventory.warehouses'),'material':ref('Material','inventory.materials'),'group':F('Grupo de localização',required=True),'subgroup':F('Subgrupo de localização',required=True),'shelf':F('Estante / endereço físico',required=True)})
 policy={'model':choice('Controle','Quantidade|Consumo mensal'),'minimum':qty('Estoque mínimo'),'average':qty('Estoque médio'),'maximum':qty('Estoque máximo'),'reorder_percent':F('Reposição sobre o máximo (%)','percent'),'minimum_months':F('Meses mínimos','integer'),'maximum_months':F('Meses máximos','integer'),'history_months':F('Meses para média de consumo','integer')}
 from copy import deepcopy
 r['warehouses']['fields'].update(restricted=F('Restringir movimentação por usuário','boolean'),**deepcopy(policy))
 r['warehouses']['fields']['model']['required']=False
 r['policies']=R('Regras de reposição por material',{**base(),'warehouse':ref('Almoxarifado','inventory.warehouses'),'material':ref('Material','inventory.materials'),**policy})
 r['accounting_rules']=R('Contabilização do estoque',{**base(),'warehouse':ref('Almoxarifado específico (vazio = padrão da entidade)','inventory.warehouses',False),'fact':choice('Fato','Entrada|Saída|Trânsito de saída|Trânsito de entrada|Devolução|Ganho de inventário|Perda de inventário|Baixa de obsoleto'),'debit':ref('Conta a débito','finance.accounts'),'credit':ref('Conta a crédito','finance.accounts'),'legal_basis':text('Fundamentação e orientação contábil',True)},operations=['approve_stock_accounting','retire_stock_accounting'])
 r['commissions']=R('Comissões de inventário',{**base(),'publication':day('Publicação da portaria',True),'start':day('Início da vigência',True),'end':day('Fim da vigência',True)},operations=['seal_stock_commission'])
 r['commission_members']=R('Integrantes das comissões',{**base(),'commission':ref('Portaria','inventory.commissions'),'cpf':F('CPF','cpf',True),'position':F('Cargo na comissão',required=True)})
 r['counts']['fields']['ordinance']['required']=False
 r['counts']['fields']['commission']['required']=False
 r['counts']['fields'].update(commission_order=ref('Portaria e comissão formalizada','inventory.commissions',False))
 r['quotas']=R('Cotas de materiais',{**base(),'cost_center':ref('Centro de custo (inclui subordinados)','inventory.cost_centers'),'material':ref('Material individual','inventory.materials',False),'material_group':F('Grupo de materiais (quando não escolher material)'),'period':F('Competência','month',True),'quantity':qty('Cota quantitativa (zero = sem limite)'),'amount':money('Cota financeira (zero = sem limite)')})
 r['requisitions']=R('Requisições',{**base(),'type':choice('Finalidade','Material|Compra'),'department':ref('Órgão requisitante','inventory.departments'),'cost_center':ref('Centro de custo','inventory.cost_centers'),'warehouse':ref('Almoxarifado','inventory.warehouses'),'date':day('Solicitação',True),'justification':text('Justificativa',True)},operations=['approve_requisition','cancel_requisition'])
 r['requisition_items']=R('Itens requisitados',{**base(),'requisition':ref('Requisição','inventory.requisitions'),'material':ref('Material','inventory.materials'),'quantity':qty('Quantidade solicitada',True),'unit_price':money('Preço unitário estimado',True)},operations=['deliver_requisition','return_requisition','cancel_requisition_balance'])
 r['purchase_links']=R('Vínculos de compra e licitação',{**base(),'requisition_item':ref('Item do pedido de compra','inventory.requisition_items'),'procurement_item':ref('Item do processo licitatório','procurement.items'),'warehouse':ref('Almoxarifado destinatário','inventory.warehouses'),'quantity':qty('Quantidade vinculada',True),'date':day('Vinculação',True),'research_number':F('Número da pesquisa de preços',required=True),'research_date':day('Data da pesquisa',True)},operations=['approve_purchase_link','cancel_purchase_link'])
 r['authorizations']=R('Autorizações de fornecimento',{**base(),'requisition':ref('Requisição de compra','inventory.requisitions',False),'process':ref('Processo homologado','procurement.processes'),'supplier':ref('Fornecedor','procurement.suppliers'),'commitment':ref('Empenho','finance.commitments'),'warehouse':ref('Almoxarifado destinatário','inventory.warehouses'),'date':day('Autorização',True),'research_number':F('Número da pesquisa de preços',required=True),'research_date':day('Pesquisa de preços',True)},operations=['approve_supply_authorization','cancel_supply_balance'])
 r['authorization_items']=R('Itens autorizados',{**base(),'authorization':ref('Autorização','inventory.authorizations'),'purchase_link':ref('Vínculo com pedido de compra','inventory.purchase_links',False),'procurement_item':ref('Item da contratação','procurement.items'),'material':ref('Material','inventory.materials'),'quantity':qty('Quantidade autorizada',True),'unit_price':money('Preço unitário autorizado',True)})
 r['invoices']=R('Notas fiscais e recebimentos',{**base(),'supplier':ref('Emitente','procurement.suppliers'),'number':F('Número da nota',required=True),'series':F('Série',required=True),'model':F('Modelo',required=True),'type':choice('Documento','Material|Serviço|Bem patrimonial'),'authorization':ref('Autorização de fornecimento','inventory.authorizations',False),'commitment':ref('Empenho (serviço / patrimônio)','finance.commitments',False),'date':day('Recebimento',True),'issued_at':day('Emissão',True),'access_key':F('Chave de acesso eletrônica')},operations=['suggest_authorized_items','post_inventory_invoice'])
 r['invoice_items']=R('Itens de notas fiscais',{**base(),'invoice':ref('Nota fiscal','inventory.invoices'),'authorization_item':ref('Item autorizado','inventory.authorization_items',False),'material':ref('Material','inventory.materials',False),'quantity':qty('Quantidade recebida',True),'unit_price':money('Preço unitário',True),'batch':F('Lote'),'expiry':day('Validade'),'asset_class':ref('Classificação patrimonial','assets.classes',False),'asset_location':F('Localização patrimonial'),'asset_owner':F('Responsável pelo bem')})
 r['movements']['fields']['type']['options']+=['Implantação','Baixa de obsoleto']
 r['movements']['fields'].update(commitment=ref('Empenho da compra','finance.commitments',False), requisition_item=ref('Item requisitado','inventory.requisition_items',False), invoice_item=ref('Item da nota fiscal','inventory.invoice_items',False))
 r['movements']['operations']+=['writeoff_obsolete']
 C['procurement']['resources']['processes']['fields'].update(resource_request_date=day('Solicitação de recursos orçamentários'),technical_opinion_date=day('Data do parecer técnico'),legal_opinion_date=day('Data do parecer jurídico'))
 C['inventory']['description']='Requisições, fornecimento, notas fiscais, estoque, contabilização e consumo por centro de custo.'

LABELS={'approve_purchase_link':'Vincular pedido à licitação','cancel_purchase_link':'Cancelar vínculo de compra','approve_stock_accounting':'Aprovar regra contábil','retire_stock_accounting':'Encerrar regra contábil','seal_stock_commission':'Formalizar comissão','approve_requisition':'Aprovar requisição','cancel_requisition':'Cancelar requisição','deliver_requisition':'Entregar material','return_requisition':'Devolver material','cancel_requisition_balance':'Cancelar saldo pendente','approve_supply_authorization':'Autorizar fornecimento','cancel_supply_balance':'Cancelar saldo autorizado','suggest_authorized_items':'Sugerir itens da autorização','post_inventory_invoice':'Conferir e efetivar recebimento','writeoff_obsolete':'Baixar material obsoleto'}
