"""Matriz conservadora: ausência de evidência nunca é tratada como atendimento."""
import json
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
source=json.loads((ROOT/'docs/anexo-iii-itens.json').read_text(encoding='utf-8'))
covered={}
def mark(module,numbers,status,coverage,before='Não havia módulo especializado nem rotina específica para este requisito.'):
 for n in numbers:covered[f'{module}.{n}']=(status,coverage,before)
mark('general',[3,7,8,10,12,16,18],'Implementado','Recursos existentes de autenticação, grupos, permissões, agenda de acesso, auditoria, atalhos e chamados. Evidências: auth.py, admin.py, records.py e tests/test_system.py.','Recurso já presente na base anterior; preservado nesta ampliação.')
mark('general',[5,11],'Implementado','Chaves estrangeiras, vínculos tipados, bloqueio de exclusão vinculada e interface servida pelo servidor. erp_core.py, erp_schema.sql, tests/test_erp.py.','Integridade relacional e interface web já existentes; ampliadas para os cadastros integrados.')
mark('general',[1,2,4,9,13,15],'Parcial','A base oferece interface web, ajuda, aprovações, manutenção controlada e exportações. Não há homologação de Internet Explorer; ajuda contextual detalhada dos novos fluxos, dupla custódia configurável para toda operação, formatos completos e condições específicas destas cláusulas ainda exigem complementação. A assinatura A1 foi implementada separadamente no item general.17.','Recursos transversais presentes, com limites registrados na matriz do edital original.')
mark('general',[6],'Dependência externa','Acesso remoto depende da publicação HTTPS e configuração de infraestrutura institucional.','Instalação local e autenticação por conta local.')
mark('cloud',range(1,13),'Dependência externa','Não comprovado por esta instalação local. Exige contratação/configuração de nuvem, certificações, redundância, operação, monitoramento e evidências descritas integralmente nesta cláusula. Backup local criptografado não comprova nuvem certificada.','Não existia infraestrutura de nuvem homologada.')
mark('control',[1,3,4,14,17,18,24,28,48,49,64,65,80,81],'Implementado','Interface web, entidade/exercício, obrigações recorrentes com ajuste do último dia do mês, ocorrências, encerramento/reabertura com justificativa e pareceres editáveis. erp_catalog.py, erp_operations.py e tests/test_erp.py. Conferir o cadastro correspondente ao texto integral.')
mark('control',[5,7,9,10,11,12,13,15,19,20,21,22,32,33,34,37,38,39,40,41,47,50,53,55,57,58,59,63,66,69,71,73,74,75,79,82,85],'Parcial','Cadastros de entidades, responsáveis textuais, verificações, ocorrências, anexos e pareceres versionados disponíveis. Faltam detalhamentos da cláusula, calendário visual completo, comunicação, regras oficiais de verificação e consolidação específica dos relatórios. Fontes: erp_catalog.py, erp_operations.py, erp_api.py.')
mark('control',[2,8,16,23,25,26,27,29,30,31,36,54,56,70,72],'Dependência externa','Carga oficial, atualização e comunicação externa não implementadas. Campos SICONFI/CAUC/Convênios identificam registros locais e não representam integração ou sincronização. Exige conector, regras e ambiente de validação.')
mark('finance',range(1,230),'Não implementado','Sem evidência de atendimento integral desta cláusula. Existem execução de dotação/empenho/liquidação/pagamento, receita, partidas dobradas e planejamento básicos. Não equivalem a PCASP/MSC, demonstrativos oficiais, rotinas tributárias, prestações legais ou tesouraria completa. Consultar o texto integral e docs/ANALISE-ANEXO-III.md.')
mark('people',[10],'Implementado','Histórico imutável por usuário para inclusão, alteração e exclusão de servidor e dependentes; consultas registradas. erp_api.py, erp_core.py, erp_schema.sql.')
mark('people',[2,3,5,6,7,9,11,19,20,32,34,35,48,49,51,63],'Parcial','Cargos/vagas, vínculos, dependentes, verbas, afastamentos, tabelas aprovadas por outro usuário e folha RPPS parametrizada com memória, contribuição patronal/suplementar e margem consignável. Não cobre todos os regimes, benefícios, regras tributárias, lotações e cálculos previstos. erp_payroll.py e tests/test_erp.py.')
mark('people',list(range(54,58))+list(range(64,69))+list(range(87,109)),'Dependência externa','Layouts, tabelas oficiais, certificados e comunicação com eSocial/bancos/TCE ainda não implementados ou homologados. Não há transmissão simulada nem tabela tributária presumida.')
mark('procurement',[1,2,7,8,14,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,41,48,65,71,73,74,76,92,95,96,104,107,108,112,113],'Parcial','Há processos, itens, propostas, cálculo de abertura com feriados, bloqueio de fornecedor, anexos, fases, adjudicação por outro usuário, contratos/aditivos e cópia de PCA. Faltam os detalhamentos integrais da cláusula, automações, documentos e tratamentos legais específicos. erp_catalog.py e erp_operations.py.')
mark('procurement',list(range(79,89))+[93,94,101,103],'Dependência externa','Existem inclusão de contratações/contratos no PNCP e assinatura A1 local. A espécie de ato, automação ou integração específica desta cláusula ainda exige complemento; registros locais não equivalem a publicação oficial. Consulte os itens específicos de cobertura PNCP e assinatura.')
mark('auction',[1],'Dependência externa','Cadastro da plataforma, identificador externo e preparação de dados locais disponíveis. Não há envio, retorno ou disputa conectada às nove plataformas exigidas. A interface informa explicitamente que a preparação não transmite dados.')
mark('inventory',[1,3],'Implementado','Almoxarifados interligados, transferência com saldo indisponível em trânsito, recebimento único com data, custo e responsável e histórico por origem/destino. Teste com 1.001 unidades e transferência entre meses. tests/test_inventory_controls.py; erp_operations.py; inventory_reports.py.')
mark('inventory',[2,6,7],'Implementado','Bloqueio impede cadastros vinculados e movimentações; itens vencidos e materiais obsoletos são rejeitados, ressalvada a rotina aprovada de baixa do item 27. inventory_core.py; erp_operations.py; tests/test_inventory_finance_atomicity.py.')
mark('inventory',[4,5,8,9],'Implementado','Órgãos e responsáveis por exercício; grupos/subgrupos; localizações físicas; controle por quantidade ou consumo mensal com parâmetros por almoxarifado e substituição por material. Sugestão calculada com saldo virtual e meses completos anteriores. inventory_catalog.py; inventory_reports.py; tests/test_inventory.py.')
mark('inventory',[10,12,13,14],'Implementado','Portarias, vigência, integrantes CPF/cargo e formalização; administrador define permissões individuais por almoxarifado/órgão; cotas financeiras e quantitativas por material/grupo em centros hierárquicos, alertas e notificações de extrapolação. inventory_core.py; inventory_api.py; inventory_operations.py; tests/test_inventory_controls.py.')
mark('inventory',[11,18,28,29],'Implementado','Notas de materiais, serviços e patrimônio com bloqueio de duplicidade; vínculo à autorização e fornecedor adjudicado; itens sugeridos pelo saldo, recebimentos parciais, reserva do empenho e liquidação simultânea ao ingresso, com rollback integral em falhas. tests/test_inventory.py; tests/test_inventory_finance_atomicity.py; inventory_operations.py.')
mark('inventory',[15,20,23,24,25],'Implementado','Relatórios de consumo/média/ABC, reposição, movimentos unificados e balancete mensal ou exercício completo; filtros combinados por almoxarifado, material, grupo/subgrupo e período; CSV/PDF e assinatura conforme configuração institucional. inventory_reports.py; inventory_api.py; tools/browser_inventory_check.py.')
mark('inventory',[16,17],'Implementado','Entrega parcial, saldo pendente e cancelamento justificado; devolução total/parcial vinculada à entrega original e valor de custo, recompondo saldo disponível. Saldos e documentos imutáveis conferidos por testes e fluxo de navegador. inventory_operations.py; tests/test_inventory.py; tools/browser_inventory_check.py.')
mark('inventory',[19,21,22],'Implementado','Vínculo aprovado entre item do pedido e item licitado, saldo virtual sem duplicação das autorizações; tela única reúne pesquisa número/data, processo/modalidade, fases e datas registradas, solicitação de recursos, pareceres, empenho, autorização e notas. Datas ausentes não são presumidas. inventory_purchases.py; inventory_api.py; static/inventory-ui.js; tests/test_inventory_controls.py.')
mark('inventory',[26,27],'Implementado','Partidas contábeis imediatas e atômicas com o estoque, regras de débito/crédito aprovadas por outra pessoa, por entidade/exercício/almoxarifado; ausência de parametrização desfaz o movimento. Baixa específica de obsoletos com aprovação e justificativa. inventory_core.py; inventory_operations.py; tests/test_inventory_finance_atomicity.py.')
mark('inventory',[30,31],'Implementado','Tabelas públicas oficiais do Siscomex/MDIC carregadas, pesquisa por código/descrição, validação de códigos e vigência NCM, vínculo no cadastro, atualização administrativa com origem/hash e versões preservadas. Versão obtida em 23/09/2026: 10.515 NCM e 920 NBS. inventory_classifications.py; schemas/classifications; tools/browser_inventory_check.py.')
mark('assets',[1,2,4,5,7,11,12,14,18,19,20,21,23],'Parcial','Classes com contas/vida útil/residual, bens próprios/alugados/comodato, depreciação mensal ou por produção, transferência individual, baixa aprovada e bloqueio durante inventário. Faltam detalhamentos, reavaliação, movimentos em lote, integração contábil automática e demonstrativos oficiais. erp_operations.py; tests/test_erp.py.')
mark('bi',[1,2,4,5],'Parcial','Painel responsivo por entidade/exercício mostra contagens reais por módulo/cadastro/situação, respeitando permissões e sigilo. Indicadores financeiros e fiscais específicos, comparações, personalização e demais métricas ainda não implementados. erp_api.py /erp/insights e static/erp-ui.js.')
mark('bi',[3],'Dependência externa','O painel existe localmente; hospedagem certificada não foi contratada/configurada.')
mark('fleet',[1,4,5,9,12,14,15,17,18,20,21,22,23,24,25],'Parcial','Motoristas/CNH, veículos vinculados ao patrimônio, abastecimentos com compatibilidade/capacidade, deslocamentos, reservas com conflito, despesas e bloqueio temporal. Faltam campos completos, tanques, itens agregados, importação de cartões, granularidade por repartição e relatórios específicos.')
mark('fleet',[26,27],'Implementado','Alteração de placa registra placa anterior, responsável e data no histórico; movimentos anteriores ao bloqueio temporal são rejeitados. erp_operations.py.')
mark('social',[4,11,16,38,59,61,62,63,65,66,67,68,69,70,72,74,77,78,82,87,88,89,90,103,104,105,106,107,108,109,110,111,112,113,114,115,127,136,170,173,176,178,180,181,182,188,194,196,204,208,209,210,216,258,259,260,262,263,264,268,270,271,272,273,274,275,276,279,300,301,302,303,304,305,314,315,320,321,322,332,333,334,335,336,337,338,339,340,341,342,344,345,346,348,349,350,352,353,354,355,356,357,358,359,363,364,365,366,367,368,370,371,387,388,389,390,391,392,394,395,397,399,400],'Parcial','Núcleo disponível: pessoas/famílias/membros, programas, agenda com conflito, atendimento, autorização de acesso sigiloso, anexos, benefícios com carência/capacidade, inscrições habitacionais e OSC/plano/prestação parametrizada. Estoque utiliza módulo próprio. Não cobre integralmente a cláusula: faltam campos e fluxos especializados, recortes por profissional/unidade, automações e documentos específicos.')
mark('social',list(range(280,291))+list(range(401,420))+list(range(116,120)),'Dependência externa','Assinatura A1 de anexos está disponível. Fluxos específicos de ICP-Brasil, SMS ou bases oficiais descritos nesta cláusula ainda precisam de conectores ou complementos próprios, layouts e autorização institucional; a assinatura genérica não comprova atendimento integral da cláusula.')
mark('works',[10,11,12,16,18,25,29,30,38,40,41,45],'Implementado','Planilha por item, BDI/desconto, sequência de medições com limite cumulativo de 100%, diário aprovado por outro usuário, pagamento limitado ao saldo e liberação da retenção após recebimento/prazo; fornecedores, grupos/permissões e documentos protegidos. Limite de 500 KB por documento. erp_operations.py, erp_api.py; tests/test_erp.py.')
mark('works',[1,2,3,4,5,6,7,8,9,13,15,19,20,21,22,23,24,26,27,28,31,33,34,35,39,42,43,44],'Parcial','Cadastros de obra, itens, cronograma por item, diário, medições, pagamentos e anexos disponíveis. Faltam todos os detalhes da cláusula, colaboração restrita por obra, importação/revisão de planilhas, consolidações e relatórios especializados. Coordenadas não implementam mapa.')
mark('social',[83,84,86,114],'Implementado','Benefício vinculado a insumo/quantidade e almoxarifado; concessão aprovada produz saída de estoque na mesma transação e desfaz tudo se faltar saldo. Agenda permite cancelamento com motivo e libera horário. erp_social_operations.py; tests/test_erp_social_stock.py.')
mark('bi',[20,21,22,23,24,25,26,27,29,30],'Parcial','Indicadores reais de execução mensal, receitas líquidas, saldo bancário, obrigações liquidadas a pagar e folhas aprovadas, respeitando entidade, exercício e permissões. Faltam os recortes, comparações, gráficos e condições adicionais da cláusula. erp_insights.py; tests/test_erp_flows.py.')
# Itens financeiros identificados por evidência de rotina, sempre parciais quando o texto exige condições adicionais.
for r in source['items']:
 if r['module']=='finance' and any(term in r['text'].lower() for term in ['empenho','liquida','pagamento','partidas','plano de contas','ppa','programas','indicadores','fonte de recurso','encerramento','contas bancárias']):
  mark('finance',[r['item']],'Parcial','Implementado núcleo tipado de contas/fontes/planejamento, dotação, empenho, liquidação, pagamento, arrecadação, partida dobrada, estorno e bloqueio de período. Há controles de saldo, data, entidade, exercício e versão. Esta cláusula contém condições adicionais ainda não cobertas; não há homologação fiscal/contábil ou layouts oficiais. erp_operations.py; tests/test_erp.py.','Existiam apenas cadastros preliminares de planejamento e documentos, sem motor de execução financeira.')
# Ampliação de integrações: evidência específica, sem declarar o anexo integralmente atendido.
mark('control',[25,26,29],'Parcial','Consulta real ao extrato de entregas Siconfi, sincronização por entidade/exercício, vínculo explícito com ocorrência, histórico e notificação de mudança de status. Não há agenda periódica automática, geração/envio de declarações ou regras completas do ranking. integration_siconfi.py; tests/test_siconfi_agenda.py; docs/INTEGRACOES-E-PROVA-DE-CONCEITO.md.')
mark('procurement',[79,81,82,85,86,88],'Parcial','Inclusão PNCP de contratações e contratos com documento PDF selecionado, pacote imutável, dupla revisão, envio explícito, recibo e histórico, com acesso pelo cadastro de origem. Testes locais de protocolo e concorrência; credenciamento/homologação externa pendentes. Não cobre todas as espécies de ato, retificações, atas e PCA. integration_publications.py, pncp_payloads.py; tests/test_integrations.py.')
mark('auction',[1],'Dependência externa','As nove plataformas constam na central administrativa com situação técnica explícita e registro institucional. Não há conector de transmissão/retorno implementado para essas plataformas. Documentação de parceiro, credenciamento, implementação e homologação permanecem necessários. integration_catalog.py; docs/INTEGRACOES-E-PROVA-DE-CONCEITO.md.')
# Integrações de diretório, assinatura e eSocial: conector pronto pode aguardar somente credencial.
mark('general',[14],'Implementado','LDAPS/StartTLS com certificado do servidor validado, busca e bind do usuário, vínculo explícito com conta local, permissões e horários preservados, sem fallback de senha, revogação de sessões e administrador local de recuperação. Aguarda os dados do diretório institucional. integration_directory.py; auth.py; tests/test_enterprise_integrations.py.')
mark('general',[17],'Implementado','Assinatura configurável globalmente, por módulo ou relatório; PDFs PAdES, demais formatos em pacote CMS destacado com original, certificado, hashes e metadados. Certificado A1, autorização dos assinantes e guarda imutável cifrada na central. Aguarda certificado institucional. integration_signatures.py; tests/test_enterprise_integrations.py; tests/test_enterprise_controls.py.')
mark('people',[95],'Implementado','Cofre A1 com validação de senha, chave, validade temporal e metadados; cadastro completo do outorgado e vigência da procuração; alertas internos de vencimento em até 30 dias, por administrador, na abertura da conta e consulta periódica de notificações. Envio bloqueado fora da vigência cadastrada. A cadeia ICP-Brasil/revogação é verificada pelo destinatário e não atestada pelo teste local. integration_certificate_alerts.py; tests/test_enterprise_controls.py.')
mark('people',[96,103,104,105,106,107],'Implementado','Importação de XMLs S-1.3 oficiais, assinatura XML RSA-SHA256 com A1, agrupamento/revisão, SOAP 1.1 com TLS mútuo em endpoints oficiais, protocolo, status/recibos/motivos de rejeição por evento, correção e novo lote para rejeições inequívocas. Histórico e retornos cifrados preservados; resultado incerto não permite duplicação. Aguarda certificado/procuração e credenciamento institucional; protocolo validado localmente com respostas controladas. integration_esocial*.py; tests/test_esocial*.py; tests/test_enterprise_controls.py.')
mark('people',[102],'Parcial','XMLs de envio e retorno validados nos XSDs oficiais S-1.3 NT06 com CNPJ alfanumérico; conferidos ID, empregador, grupo, ambiente e assinatura. Regras condicionais negociais adicionais descritas no MOS não são integralmente validadas localmente. integration_esocial_xml.py.')
mark('people',[100,108],'Parcial','Lotes por entidade/ambiente, eventos com estados, recibos e mensagens, XMLs assinados e retornos preservados disponíveis para download. Faltam filtros completos por servidor/competência, geração e retificação automática a partir da folha, conciliação de totalizadores e controle integrado de fechamento. integration_esocial.py; static/esocial-ui.js.')
items=[]
for r in source['items']:
 status,coverage,before=covered.get(r['key'],('Não implementado','Não foi encontrada rotina específica que comprove atendimento integral do requisito. O texto completo foi preservado para implementação e homologação posteriores.','Não havia implementação específica identificada na base anterior.'))
 if r['module']=='transparency':
  before='Existia portal de publicações aprovadas, com segregação de rascunhos.'
  coverage='O portal existente publica registros aprovados. Não há evidência para declarar atendida esta cláusula específica: faltam integração e detalhamentos dos dados, filtros, séries, visualizações e documentos exigidos.'
 items.append({**r,'status':status,'coverage':coverage,'before':before})
note='Matriz técnica conservadora, não é laudo de conformidade. A implementação NÃO atende 100% do Anexo III. Itens parciais exigem complementação; integrações, infraestrutura e cálculos oficiais dependem de homologação. A numeração social salta de 290 para 300 no PDF original.'
result={**source,'items':items,'note':note,'status_counts':dict(Counter(x['status'] for x in items))}
(ROOT/'docs/anexo-iii-conformidade.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
lines=['# Matriz do Anexo III','',note,'','Fonte: `ANEXO III.pdf`, 100 páginas, páginas impressas 84–183. 1.314 itens numerados catalogados, incluindo linhas de subitens numeradas no original.','','| Item | Página | Situação | Cobertura / pendências |','|---|---:|---|---|']
for r in items:lines.append(f"| {r['key']} | {r['page']} | {r['status']} | {r['coverage'].replace('|','/')} |")
(ROOT/'docs/MATRIZ-ANEXO-III.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(result['status_counts'])
